spring.application.name=Forgex

spring.datasource.url=jdbc:postgresql://localhost:5432/Forgex
spring.datasource.username=postgres
spring.datasource.password=Sidd@2004
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

project.image=images/